version: '3.8'

services:
  txbot:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "node"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 30s 